apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.spec.app}}
  name: {{ .Values.spec.app}}-service
spec:
  ports:
  - name: {{ .Values.spec.app}}-port
    port: {{.Values.spec.containerPort}}
    protocol: TCP
    targetPort: {{.Values.spec.containerPort}}
  selector:
    app: {{ .Values.spec.app}}
  type: {{.Values.service.type}}

  
